# .github/workflows/yolo5.yml
name: Build and Push Yolo5
on:
  push:
    branches: [main]
    paths:
      - 'yolo5/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Latest Tag from Docker Hub
        id: get-latest-tag
        run: |
          # Fetch the latest tag from Docker Hub for guymeltzer/yolo5
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/guymeltzer/yolo5/tags/?page_size=25" | \
            jq -r '.results[] | .name' | \
            grep -E '^1\.0\.[0-9]+$' | \
            sort -V | \
            tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
            echo "No valid tag found, starting with 1.0.98"
            LATEST_TAG="1.0.98"
          fi
          # Extract the patch version and increment it
          PATCH_VERSION=$(echo $LATEST_TAG | cut -d'.' -f3)
          NEW_PATCH=$((PATCH_VERSION + 1))
          NEW_TAG="1.0.$NEW_PATCH"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t guymeltzer/yolo5:${{ steps.get-latest-tag.outputs.NEW_TAG }} yolo5/
          docker push guymeltzer/yolo5:${{ steps.get-latest-tag.outputs.NEW_TAG }}
          # Optionally tag as 'latest' as well
          docker tag guymeltzer/yolo5:${{ steps.get-latest-tag.outputs.NEW_TAG }} guymeltzer/yolo5:latest
          docker push guymeltzer/yolo5:latest
